version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecurePassword123!
      MYSQL_DATABASE: todo_list
      MYSQL_USER: custom_user
      MYSQL_PASSWORD: AnotherStrongPassword456!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
